### ISSUE TITLE
Use shared Clerk functions

### ISSUE THREAD

**Issue by wobsoriano** [spirit-led-software/clerk-solidjs#115]
### Feature Description

We've recently exposed some commonly used functions across SDKs in our `@clerk/shared` module.

1. `loadClerkJsScript` - You can replace your [current implementation](https://github.com/spirit-led-software/clerk-solidjs/blob/3acb2ce86f7e6ab0c324fb3c2ffe39ff0641e47b/packages/clerk-solidjs/src/utils/load-clerk-js-script.ts) with [this one](https://github.com/clerk/javascript/blob/main/packages/shared/src/loadClerkJsScript.ts).

2. `deriveState` - We've also exposed [this](https://github.com/clerk/javascript/blob/main/packages/shared/src/deriveState.ts). Feel free to use that instead of your  [current implementation](https://github.com/spirit-led-software/clerk-solidjs/blob/master/packages/clerk-solidjs/src/utils/derive-state.ts).

### Use Case

Eliminate duplicate code and make SDKs consistent

**Comment by ian-pascoe** [comment]
Thank you for that information. I will tackle that next week!

**Comment by ian-pascoe** [comment]
Shared functions are now being used
